---
title: "Analyse der NeFo-GEOEssential-Umfrage zur Biodiversitätsdatenintegration"
date: "2018"
header-includes:
   - \usepackage{longtable}
output:
  pdf_document:
    toc: yes
  documentclass: article
  html_document:
    toc: yes
  classoption: a4paper
  graphics: yes
---

# Einleitung
Dieses ist das Skript der Analyse der NeFo-GEOEssential-Umfrage zur Biodiversitätsdatenintegration. Das Skrpit ist verfügbar unter https://github.com/JonasGeschke/nefo_bdi


# Einstellungen

```{r set wd - CHOOSE, eval=FALSE}
# If your working directory is not already specified because you are running this
# script within a project, you will need to use the setwd() function below to set
# the path of your working directory. In order to do this just copy the path
# between the quote signs.
# Please note: The different levels of the path need to be separated by slashes
# ("/"), not by backslashes ("\") which are the windows default.
# 
# setwd("")

setwd("U:/Workshops_orga/Biodiv_Datenintegration/Umfrage/R") # Jonas
```

```{r install packages, eval=FALSE}
# Installing required packages if not installed yet
if("xlsx" %in% rownames(installed.packages())   == FALSE){
  install.packages("xlsx")}
if("splus2R" %in% rownames(installed.packages())   == FALSE){
  install.packages("splus2R")}
if("RColorBrewer" %in% rownames(installed.packages())   == FALSE){
  install.packages("RColorBrewer")}
```

```{r set additional functions, eval=FALSE}
'%!in%' <- function(x,y)!('%in%'(x,y))
```


# Qualitative Fragen

```{r qualitative Ergebnisse roh, eval=FALSE}
## Load raw data
Raw_deutsch <- read.csv2(file = "Daten/umfrage_zur_biodiversitatsdatenintegration_in_deutschland.csv", 
                         header = F, sep = ";", fileEncoding = "UTF8", 
                         na.strings = "", stringsAsFactors = FALSE)
Raw_englisch <- read.csv2(file = "Daten/questionnaire_on_integration_of_biodiversity_data_in_germany.csv", 
                          header = F, sep = ";", fileEncoding = "UTF8", 
                          na.strings = "", stringsAsFactors = FALSE)

gesamt <- rbind(Raw_deutsch, Raw_englisch[-c(1:3),])
names(gesamt) <- gesamt[3,]
gesamt <- gesamt[-c(1:3),]


############### SPALTEN ANPASSEN ###############
# Qualitative Antworten
Q1_1 <- gesamt[,c(1:5)]
names(Q1_1) <- c("Datenbereitstellung", "Datenaufbereitung", "Datenverschmelzung", "anderes", "Info")
xlsx::write.xlsx(Q1_1, file = "Q1_1.xls")

Q1_3 <- gesamt[,7]
xlsx::write.xlsx(Q1_3, file = "Q1_3.xls")

Q1_4 <- gesamt[,c(8:10)]
names(Q1_4) <- c("a", "b", "c")
xlsx::write.xlsx(Q1_4, file = "Q1_4.xls")

Q1_5 <- gesamt[,c(11:13)]
names(Q1_5) <- c("a", "b", "c")
xlsx::write.xlsx(Q1_5, file = "Q1_5.xls")

Q1_6 <- gesamt[,c(14:16)]
names(Q1_6) <- c("a", "b", "c")
xlsx::write.xlsx(Q1_6, file = "Q1_6.xls")

Q3_2 <- gesamt[,c(29:36)]
names(Q3_2) <- c("LIDAR", "RADAR", "Multi", "Hyper", "Wärme", "Ortho", "andere", "Info")
xlsx::write.xlsx(Q3_2, file = "Q3_2.xls")

Q3_5 <- gesamt[,c(85:98)]
names(Q3_5) <- c("NBS", "EU-BS", "GAP", "Natura", "FFH", "CBD", "IPBES", "CITES", "CMS", "EUROBATS", "Ramsar", "GEO", "andere", "Info")
xlsx::write.xlsx(Q3_5, file = "Q3_5.xls")

Q3_6 <- gesamt[,c(99:101)]
Q3_6[9,1] <- NA
xlsx::write.xlsx(Q3_6, file = "Q3_6.xls")

Q4_4 <- gesamt[,c(111:112)]
names(Q4_4) <- c("Tätigkeit", "Info")
xlsx::write.xlsx(Q4_4, file = "Q4_4.xls")

Feedback <- gesamt[,118]
Feedback[c(22,43)] <- NA
xlsx::write.xlsx(Feedback, file = "Feedback.xls")
```

```{r Q1_6, eval=FALSE}
Q1_6 <- gesamt[,c(1,15:17)]

Q1_6_part <- data.frame(SID = NA, word = NA)
rows <- c(1:nrow(Q1_6))
for (r in rows){
  Q1_6_SID <- Q1_6[r,]
  Q1_6_part <- rbind(Q1_6_part, c(Q1_6_SID[1,1], Q1_6_SID[1,2]))
  Q1_6_part <- rbind(Q1_6_part, c(Q1_6_SID[1,1], Q1_6_SID[1,3]))
  Q1_6_part <- rbind(Q1_6_part, c(Q1_6_SID[1,1], Q1_6_SID[1,4]))
}
Q1_6 <- Q1_6_part[-which(is.na(Q1_6_part$word)),]
rm(Q1_6_part, Q1_6_SID, rows, r)
Q1_6$word <- splus2R::lowerCase(Q1_6$word)
xlsx::write.xlsx(Q1_6, file = "Q1_6.xls")

Q1_6 <- xlsx::read.xlsx(file = "Daten/Q1_6_cleaned.xls", sheetIndex = 1, header = TRUE, encoding = "UTF-8")
Q1_6_tb <- table(Q1_6$word)
coul <- RColorBrewer::brewer.pal(5, "Set2")
wordcloud::wordcloud(words = names(Q1_6_tb), freq = as.numeric(Q1_6_tb), min.freq = 1, random.order = FALSE, colors = coul)
```


# Quantitative Fragen

```{r quantitative Ergebnisse roh, eval=FALSE}
ergebnisse <- read.csv2(file = "Daten/ergebnisse.csv", 
                         header = TRUE, sep = ";", fileEncoding = "UTF8", 
                         na.strings = "", stringsAsFactors = FALSE)
ergebnisse[ergebnisse == "X"] <- 1
```

```{r Q1_1, eval=FALSE}
Q1_1 <- ergebnisse[,c(2:5)]
Q1_1 <- transform(Q1_1, X1_1_a = as.numeric(X1_1_a), 
                        X1_1_b = as.numeric(X1_1_b), 
                        X1_1_c = as.numeric(X1_1_c), 
                        X1_1_d = as.numeric(X1_1_d))

Q1_1_sum <- colSums(Q1_1, na.rm = TRUE)
Q1_1_rel <- 100/sum(Q1_1_sum)*Q1_1_sum
q1_1 <- barplot(Q1_1_rel,
        #main = "Mit welchem dieser Schritte der Biodiversitätsdatenintegration beschäftigen Sie sich?", 
        main = "With which of these steps of biodiversity data integration do you deal?",
        sub = paste("total n", "=", length(rowSums(Q1_1, na.rm=T)!=0), sep = " "),
        #names.arg = c("Datenbereitstellung", "Datenaufbereitung", "Datenverschmelzung", "Mit keinem 'dieser' Schritte"),
        names.arg = c("Making data available", "Data processing", "Data merging", "None of the above"),
        ylim = c(0,max(Q1_1_rel)+5), yaxt='n', col = rgb(69,121,163, max=255))
text(x = q1_1, y = Q1_1_rel, label = paste(round(Q1_1_rel, digits = 0), "%", " \n ", "n = ", Q1_1_sum, sep = ""), pos = 3, cex = 1, col = "black")
```

```{r Q1_2, eval=FALSE}
Q1_2 <- factor(ergebnisse$X1_2, levels = c("1_2_a", "1_2_b", "1_2_c", "1_2_d"))

Q1_2_sum <- as.numeric(table(Q1_2))
names(Q1_2_sum) <- c("1_2_a", "1_2_b", "1_2_c", "1_2_d")
Q1_2_rel <- 100/sum(Q1_2_sum)*Q1_2_sum
q1_2 <- barplot(Q1_2_rel,
        #main = "Wie viel Prozent Ihrer Arbeitszeit beschäftigen Sie sich mit der Biodiversitätsdatenintegration?", 
        main = "How much of your working time do you spend dealing with biodiversity data integration?",
        sub = paste("total n", "=", length(ergebnisse$X1_2[!is.na(ergebnisse$X1_2) == T]), sep = " "),
        #names.arg = c("0 bis 25%", "26 bis 50%", "51 bis 75%", "76 bis 100%"),
        names.arg = c("0 to 25%", "26 to 50%", "51 to 75%", "76 to 100%"),
        ylim = c(0,max(Q1_2_rel)+5), yaxt='n', col = rgb(128,179,78, max=255))
text(x = q1_2, y = Q1_2_rel, label = paste(round(Q1_2_rel, digits = 0), "%", " \n ", "n = ", Q1_2_sum, sep = ""), pos = 3, cex = 1, col = "black")
```

```{r Q2_1, eval=FALSE}
Q2_1 <- factor(ergebnisse$X2_1, levels = c("2_1_a", "2_1_b"))

Q2_1_sum <- as.numeric(table(Q2_1))
#names(Q2_1_sum) <- c("Ja", "Nein")
names(Q2_1_sum) <- c("Yes", "No")
Q2_1_rel <- 100/sum(Q2_1_sum)*Q2_1_sum
q2_1 <- barplot(Q2_1_rel,
        #main = "Haben Sie bereits von den FAIR-Prinzipien gehört?", 
        main = "Were you already aware of the FAIR principles?",
        sub = paste("total n", "=", length(ergebnisse$X2_1[!is.na(ergebnisse$X2_1) == T]), sep = " "),
        #names.arg = c("Ja", "Nein"),
        names.arg = c("Yes", "No"),
        ylim = c(0,max(Q2_1_rel)+5), yaxt='n')
text(x = q2_1, y = Q2_1_rel, label = paste(round(Q2_1_rel, digits = 0), "%", " \n ", "n = ", Q2_1_sum, sep = ""), pos = 3, cex = 1, col = "black")

labls <- paste(names(Q2_1_rel), "\n", round(Q2_1_rel, digits = 0), "%", sep = "")
pie(Q2_1_rel, labels = labls, col = c("forestgreen", "firebrick"),
    #main = "Haben Sie bereits von den FAIR-Prinzipien gehört?"
    main = "Were you already aware of the FAIR principles?")
````


```{r Q2_2, eval=FALSE}
Q2_2 <- ergebnisse[,c(19:22)]
Q2_2_table <- data.frame(matrix(NA, ncol = 4, nrow = 4))
names(Q2_2_table) <- c("2_2_a", "2_2_b", "2_2_c", "2_2_d")
Q2_2_table[1,1] <- length(which(Q2_2$X2_2_1 == "2_2_a"))
Q2_2_table[1,2] <- length(which(Q2_2$X2_2_1 == "2_2_b"))
Q2_2_table[1,3] <- length(which(Q2_2$X2_2_1 == "2_2_c"))
Q2_2_table[1,4] <- length(which(Q2_2$X2_2_1 == "2_2_d"))
Q2_2_table[2,1] <- length(which(Q2_2$X2_2_2 == "2_2_a"))
Q2_2_table[2,2] <- length(which(Q2_2$X2_2_2 == "2_2_b"))
Q2_2_table[2,3] <- length(which(Q2_2$X2_2_2 == "2_2_c"))
Q2_2_table[2,4] <- length(which(Q2_2$X2_2_2 == "2_2_d"))
Q2_2_table[3,1] <- length(which(Q2_2$X2_2_3 == "2_2_a"))
Q2_2_table[3,2] <- length(which(Q2_2$X2_2_3 == "2_2_b"))
Q2_2_table[3,3] <- length(which(Q2_2$X2_2_3 == "2_2_c"))
Q2_2_table[3,4] <- length(which(Q2_2$X2_2_3 == "2_2_d"))
Q2_2_table[4,1] <- length(which(Q2_2$X2_2_4 == "2_2_a"))
Q2_2_table[4,2] <- length(which(Q2_2$X2_2_4 == "2_2_b"))
Q2_2_table[4,3] <- length(which(Q2_2$X2_2_4 == "2_2_c"))
Q2_2_table[4,4] <- length(which(Q2_2$X2_2_4 == "2_2_d"))
Q2_2 <- t(Q2_2_table)
rm(Q2_2_table)
names(Q2_2) <- c("2_2_1", "2_2_2", "2_2_3", "2_2_4")

Q2_2_sum <- as.numeric(colSums(Q2_2))
names(Q2_2_sum) <- c("2_2_1", "2_2_2", "2_2_3", "2_2_4")
Q2_2_rel <- 100/Q2_2_sum*Q2_2
#row.names(Q2_2_rel) <- c("unwichtig", "eher nicht wichtig", "eher wichtig", "sehr wichtig")
row.names(Q2_2_rel) <- c("not important", "rather not important", "rather important", "very important")
q2_2 <- barplot(Q2_2_rel,
        #main = "Als wie wichtig erachten Sie die vier FAIR-Prinzipien für die Integration von Biodiversitätsdaten?", 
        main = "How important do you find the four FAIR principles for biodiversity data integration?",
        sub = paste("mean n", "=", round(mean(Q2_2_sum), digits = 0), sep = " "),
        #names.arg = c("auffindbar", "zugänglich", "harmonisiert", "nachnutzbar"),
        names.arg = c("findable", "accessible", "interoperable", "reusable"),
        ylim = c(0,max(Q2_2_rel)+10), yaxt='n',
        beside = TRUE,
        legend.text = TRUE,
        args.legend = list("topright", bty = "n"),
        col = c("firebrick", "darkorange", "yellowgreen", "forestgreen"))
text(x = q2_2, y = Q2_2_rel, label = paste(round(Q2_2_rel, digits = 0), "%", " \n ", "n = ", Q2_2, sep = ""), pos = 3, cex = 1, col = "black")
```


```{r Q2_3, eval=FALSE}
Q2_3 <- ergebnisse[,c(23:27)]
Q2_3_table <- data.frame(matrix(NA, ncol = 4, nrow = 5))
names(Q2_3_table) <- c("2_3_a", "2_3_b", "2_3_c", "2_3_d")
Q2_3_table[1,1] <- length(which(Q2_3$X2_3_1 == "2_3_a"))
Q2_3_table[1,2] <- length(which(Q2_3$X2_3_1 == "2_3_b"))
Q2_3_table[1,3] <- length(which(Q2_3$X2_3_1 == "2_3_c"))
Q2_3_table[1,4] <- length(which(Q2_3$X2_3_1 == "2_3_d"))
Q2_3_table[2,1] <- length(which(Q2_3$X2_3_2 == "2_3_a"))
Q2_3_table[2,2] <- length(which(Q2_3$X2_3_2 == "2_3_b"))
Q2_3_table[2,3] <- length(which(Q2_3$X2_3_2 == "2_3_c"))
Q2_3_table[2,4] <- length(which(Q2_3$X2_3_2 == "2_3_d"))
Q2_3_table[3,1] <- length(which(Q2_3$X2_3_3 == "2_3_a"))
Q2_3_table[3,2] <- length(which(Q2_3$X2_3_3 == "2_3_b"))
Q2_3_table[3,3] <- length(which(Q2_3$X2_3_3 == "2_3_c"))
Q2_3_table[3,4] <- length(which(Q2_3$X2_3_3 == "2_3_d"))
Q2_3_table[4,1] <- length(which(Q2_3$X2_3_4 == "2_3_a"))
Q2_3_table[4,2] <- length(which(Q2_3$X2_3_4 == "2_3_b"))
Q2_3_table[4,3] <- length(which(Q2_3$X2_3_4 == "2_3_c"))
Q2_3_table[4,4] <- length(which(Q2_3$X2_3_4 == "2_3_d"))
Q2_3_table[5,1] <- length(which(Q2_3$X2_3_5 == "2_3_a"))
Q2_3_table[5,2] <- length(which(Q2_3$X2_3_5 == "2_3_b"))
Q2_3_table[5,3] <- length(which(Q2_3$X2_3_5 == "2_3_c"))
Q2_3_table[5,4] <- length(which(Q2_3$X2_3_5 == "2_3_d"))
Q2_3 <- t(Q2_3_table)
rm(Q2_3_table)
names(Q2_3) <- c("2_3_1", "2_3_2", "2_3_3", "2_3_4", "2_3_5")

Q2_3_sum <- as.numeric(colSums(Q2_3))
names(Q2_3_sum) <- c("2_3_1", "2_3_2", "2_3_3", "2_3_4", "2_3_5")
Q2_3_rel <- 100/Q2_3_sum*Q2_3
#row.names(Q2_3_rel) <- c("sehr schlecht", "eher schlecht", "eher gut", "sehr gut")
row.names(Q2_3_rel) <- c("very bad", "rather bad", "rather good", "very good")
q2_3 <- barplot(Q2_3_rel,
        #main = "Als wie gut finden Sie die vier FAIR-Prinzipen bei Biodiversitätsdaten in Deutschland bereits umgesetzt?", 
        main = "How good do you find the use of the FAIR principles in Germany for biodiversity data?",
        sub = paste("mean n", "=", round(mean(Q2_3_sum), digits = 0), sep = " "),
        #names.arg = c("auffindbar", "zugänglich", "harmonisiert", "nachnutzbar", "insgesamt"),
        names.arg = c("findable", "accessible", "interoperable", "reusable ", "as a whole"),
        ylim = c(0,max(Q2_3_rel)+25), yaxt='n',
        beside = TRUE, 
        legend.text = TRUE,
        args.legend = list("topright", bty = "n"),
        col = c("firebrick", "darkorange", "yellowgreen", "forestgreen"))
text(x = q2_3, y = Q2_3_rel, label = paste(round(Q2_3_rel, digits = 0), "%", " \n ", "n = ", Q2_3, sep = ""), pos = 3, cex = 1, col = "black")
```

```{r Q2_4, eval=FALSE}
Q2_4 <- factor(ergebnisse$X2_4, levels = c("2_4_a", "2_4_b", "2_4_c"))

Q2_4_sum <- as.numeric(table(Q2_4))
#names(Q2_4_sum) <- c("Ja", "Nein", "In Teilen")
names(Q2_4_sum) <- c("Yes", "No", "Partly")
Q2_4_rel <- 100/sum(Q2_4_sum)*Q2_4_sum
q2_4 <- barplot(Q2_4_rel,
        #main = "Handeln Sie in Ihrer Forschung oder Arbeit bereits nach dem Prinzip des FAIRen Datenmanagements?",
        main = "Do you already deal with the FAIR principles of data management in your work?", 
        sub = paste("total n", "=", length(ergebnisse$X2_4[!is.na(ergebnisse$X2_4) == T]), sep = " "),
        #names.arg = c("Ja", "Nein", "In Teilen"),
        names.arg = c("Yes", "No", "Partly"),
        ylim = c(0,max(Q2_4_rel)+5), yaxt='n')
text(x = q2_4, y = Q2_4_rel, label = paste(round(Q2_4_rel, digits = 0), "%", " \n ", "n = ", Q2_4_sum, sep = ""), pos = 3, cex = 1, col = "black")

labls <- paste(names(Q2_4_rel), "\n", round(Q2_4_rel, digits = 0), "%", sep = "")
pie(Q2_4_rel, labels = labls, col = c("forestgreen", "firebrick", "yellowgreen"),
    #main = "Handeln Sie in Ihrer Forschung oder Arbeit \n bereits nach dem Prinzip des FAIRen Datenmanagements?"
    main = "Do you already deal with the FAIR principles of data management in your work?")
```

```{r Q3_1, eval=FALSE}
Q3_1 <- factor(ergebnisse$X3_1, levels = c("3_1_a", "3_1_b"))

Q3_1_sum <- as.numeric(table(Q3_1))
#names(Q3_1_sum) <- c("Ja", "Nein")
names(Q3_1_sum) <- c("Yes", "No")
Q3_1_rel <- 100/sum(Q3_1_sum)*Q3_1_sum
q3_1 <- barplot(Q3_1_rel,
        #main = "Nutzen Sie bereits Fernerkundungsdaten in Ihrer Arbeit?", 
        main = "Do you already use remote sensing data in your work?", 
        sub = paste("total n", "=", length(ergebnisse$X3_1[!is.na(ergebnisse$X3_1) == T]), sep = " "),
        #names.arg = c("Ja", "Nein"),
        names.arg = c("Yes", "No"),
        ylim = c(0,max(Q3_1_rel)+5), yaxt='n')
text(x = q3_1, y = Q3_1_rel, label = paste(round(Q3_1_rel, digits = 0), "%", " \n ", "n = ", Q3_1_sum, sep = ""), pos = 3, cex = 1, col = "black")

labls <- paste(names(Q3_1_rel), "\n", round(Q3_1_rel, digits = 0), "%", sep = "")
pie(Q3_1_rel, labels = labls, col = c("forestgreen", "firebrick"),
    #main = "Nutzen Sie bereits Fernerkundungsdaten in Ihrer Arbeit?"
    main = "Do you already use remote sensing data in your work?")
```

```{r Q3_2, eval=FALSE}
Q3_2 <- ergebnisse[,c(30:36)]
Q3_2 <- transform(Q3_2, X3_2_a = as.numeric(X3_2_a), 
                        X3_2_b = as.numeric(X3_2_b), 
                        X3_2_c = as.numeric(X3_2_c), 
                        X3_2_d = as.numeric(X3_2_d),
                        X3_2_e = as.numeric(X3_2_e),
                        X3_2_f = as.numeric(X3_2_f),
                        X3_2_g = as.numeric(X3_2_g))

Q3_2_sum <- colSums(Q3_2, na.rm = TRUE)
Q3_2_rel <- 100/sum(Q3_2_sum)*Q3_2_sum
q3_2 <- barplot(Q3_2_rel,
        #main = "Welche Art(en) von Fernerkundungsdaten nutzen Sie?", 
        main = "Which type(s) of remote sensing data do you use?", 
        sub = paste("total n", "=", length(which(rowSums(Q3_2, na.rm=T)!=0)), sep = " "),
        #names.arg = c("LIDAR", "RADAR", "multispektral", "hyperspektral", "Wärmebilder", "Orthophotos", "andere"),
        names.arg = c("LIDAR", "RADAR", "multispectral", "hyperspectral", "thermal", "orthophotos", "others"),
        ylim = c(0,max(Q3_2_rel)+5), yaxt='n',
        col = rgb(69,121,163,max=255))
#        col = c(RColorBrewer::brewer.pal(7, "Set2")))
text(x = q3_2, y = Q3_2_rel, label = paste(round(Q3_2_rel, digits = 0), "%", " \n ", "n = ", Q3_2_sum, sep = ""), pos = 3, cex = 1, col = "black")
```

```{r Q3_3, eval=FALSE}
Q3_3 <- ergebnisse[,c(38:43)]
Q3_3 <- transform(Q3_3, X3_3_a = as.numeric(X3_3_a), 
                        X3_3_b = as.numeric(X3_3_b), 
                        X3_3_c = as.numeric(X3_3_c), 
                        X3_3_d = as.numeric(X3_3_d),
                        X3_3_e = as.numeric(X3_3_e),
                        X3_3_f = as.numeric(X3_3_f))

Q3_3_sum <- colSums(Q3_3, na.rm = TRUE)
Q3_3_rel <- 100/sum(Q3_3_sum)*Q3_3_sum
q3_3 <- barplot(Q3_3_rel,
        #main = "Für welche(n) Zweck(e) nutzen Sie Fernerkundungsdaten?", 
        main = "For which purpose(s) do you use remote sensing data?", 
        sub = paste("total n", "=", length(which(rowSums(Q3_3, na.rm=T)!=0)), sep = " "),
        #names.arg = c("Biodiv.-Monitoring", "Pol. Berichterstattung", "Forschung", "Planung", "Beratung", "Privatwirtschaftl. Zwecke"),
        names.arg = c("Biodiv. monitoring", "Policy reporting", "Research", "Planning", "Consulting", "Other private sector purposes"),
        ylim = c(0,max(Q3_3_rel)+5), yaxt='n',
        col = rgb(128,179,78,max=255))
#        col = c(RColorBrewer::brewer.pal(6, "Set2")))
text(x = q3_3, y = Q3_3_rel, label = paste(round(Q3_3_rel, digits = 0), "%", " \n ", "n = ", Q3_3_sum, sep = ""), pos = 3, cex = 1, col = "black")
```

```{r Q3_4 NEEDS EDIT, eval=FALSE}
Q3_4 <- xlsx::read.xlsx(file = "Daten/results.xlsx", sheetIndex = 4, encoding="UTF-8")
row.names(Q3_4) <- Q3_4[,1]
Q3_4 <- Q3_4[,-1]
#names(Q3_4) <- c("sehr schlecht", "eher schlecht", "eher gut", "sehr gut", "weiß nicht")
names(Q3_4) <- c("very bad", "rather bad", "rather good", "very good", "don't know")
str(Q3_4)
Q3_4 <- t(Q3_4)

Q3_4_sum <- colSums(t(Q3_4), na.rm = TRUE)
Q3_4_rel <- 100/Q3_4_sum*t(Q3_4)
Q3_4_rel <- t(Q3_4_rel)
Q3_4_rel[,6] <- 0
q3_4 <- barplot(Q3_4_rel,
        #main = "In Ihrer Anwendung, wie gut funktioniert welche Art von Fernerkundungsdaten?", 
        main = "For biodiversity monitoring, how good does each type of remote sensing data work?", 
        sub = paste("total n", "=", length(rowSums(Q3_4, na.rm=T)!=0), sep = " "),
        #names.arg = c("LIDAR", "RADAR", "multispetral", "hyperspektral", "Wärmebilder", "Orthophotos", "andere"),
        names.arg = c("LIDAR", "RADAR", "multispectral", "hyperspectral", "thermal", "orthophotos", "others"),
        ylim = c(0,max(Q3_4_rel)+20), yaxt='n',
        beside = TRUE, 
        legend.text = TRUE,
        args.legend = list("topright", bty = "n"),
        col = c("firebrick", "darkorange", "yellowgreen", "forestgreen", "grey"))
text(x = q3_4, y = Q3_4_rel, label = paste(round(Q3_4_rel, digits = 0), "%", " \n ", "n = ", Q3_4_sum, sep = ""), pos = 3, cex = 1, col = "black")
```

```{r Q3_5, eval=FALSE}
Q3_5 <- ergebnisse[,c(86:98)]
Q3_5 <- transform(Q3_5, X3_5_a = as.numeric(X3_5_a), 
                        X3_5_b = as.numeric(X3_5_b), 
                        X3_5_c = as.numeric(X3_5_c), 
                        X3_5_d = as.numeric(X3_5_d),
                        X3_5_e = as.numeric(X3_5_e),
                        X3_5_f = as.numeric(X3_5_f),
                        X3_5_g = as.numeric(X3_5_g), 
                        X3_5_h = as.numeric(X3_5_h), 
                        X3_5_i = as.numeric(X3_5_i), 
                        X3_5_j = as.numeric(X3_5_j),
                        X3_5_k = as.numeric(X3_5_k),
                        X3_5_l = as.numeric(X3_5_l),
                        X3_5_m = as.numeric(X3_5_m))

Q3_5_sum <- colSums(Q3_5, na.rm = TRUE)
Q3_5_rel <- 100/sum(Q3_5_sum)*Q3_5_sum
q3_5 <- barplot(Q3_5_rel,
        main = "Zur Berichterstattung für welche(n) Politikprozess(e) nutzen Sie Fernerkundungsdaten?", 
        sub = paste("total n", "=", length(which(rowSums(Q3_5, na.rm=T)!=0)), sep = " "),
        names.arg = c("Deutsche Nationale Biodiversitätsstrategie", 
                                        "Europäische Biodiversitätsstrategie",
                                        "Gemeinsame Agrarpolitik der EU (GAP)",
                                        "Natura 2000",
                                        "Fauna-Flora-Habitat-Richtlinie (FFH)",
                                        "Übereinkommen über die biologische Vielfalt (CBD)",
                                        "Intergovernmental science-policy Platform on Biodiversity and Ecosystem Services (IPBES)",
                                        "Washingtoner Artenschutzabkommen (CITES",
                                        "Übereinkommen zur Erhaltung wandernder wild lebender Tierarten (CMS)",
                                        "Abkommen zur Erhaltung der europäischen Fledermauspopulationen (EUROBATS)",
                                        "Übereinkommen über Feuchtgebiete (Ramsar)",
                                        "Group on Earth Observations (GEO)",
                                        "Andere"),
        ylim = c(0,max(Q3_5_rel)+5), yaxt='n')
text(x = q3_5, y = Q3_5_rel, label = paste(round(Q3_5_rel, digits = 0), "%", " \n ", "n = ", Q3_5_sum, sep = ""), pos = 3, cex = 1, col = "black")
```

```{r Q3_7, eval=FALSE}
Q3_7 <- factor(ergebnisse$X3_7, levels = c("3_7_a", "3_7_b"))

Q3_7_sum <- as.numeric(table(Q3_7))
#names(Q3_7_sum) <- c("Ja", "Nein")
names(Q3_7_sum) <- c("Yes", "No")
Q3_7_rel <- 100/sum(Q3_7_sum)*Q3_7_sum
q3_7 <- barplot(Q3_7_rel,
        #main = "Kannten Sie das Konzept der Essentiellen Biodiversitätsvariablen (EBVs) bereits?", 
        main = "Did you already know the concept of Essential Biodiversity Variables (EBVS)?", 
        sub = paste("total n", "=", length(ergebnisse$X3_7[!is.na(ergebnisse$X3_7) == T]), sep = " "),
        #names.arg = c("Ja", "Nein"),
        names.arg = c("Yes", "No"),
        ylim = c(0,max(Q3_7_rel)+5), yaxt='n')
text(x = q3_7, y = Q3_7_rel, label = paste(round(Q3_7_rel, digits = 0), "%", " \n ", "n = ", Q3_7_sum, sep = ""), pos = 3, cex = 1, col = "black")

labls <- paste(names(Q3_7_rel), "\n", round(Q3_7_rel, digits = 0), "%", sep = "")
pie(Q3_7_rel, labels = labls, col = c("forestgreen", "firebrick"),
    #main = "Kannten Sie das Konzept der \n Essentiellen Biodiversitätsvariablen (EBVs) bereits?"
    main = "Did you already know the concept of Essential Biodiversity Variables (EBVS)?")
```

```{r Q3_8 (_1 / _2 / _3), eval=FALSE}
Q3_8 <- ergebnisse[,c(104:107)]
names(Q3_8) <- c("Klasse", "Frage1", "Frage2", "Frage3")
Q3_8 <- tidyr::separate(Q3_8, Klasse, c("K1", "K2", "K3", "K4", "K5", "K6"), sep = " - ")
Q3_8 <- tidyr::separate(Q3_8, Frage1, 
                        c("1_K1", "1_K2", "1_K3", "1_K4", "1_K5", "1_K6"), sep = " - ")
Q3_8 <- tidyr::separate(Q3_8, Frage2, 
                        c("2_K1", "2_K2", "2_K3", "2_K4", "2_K5", "2_K6"), sep = " - ")
Q3_8 <- tidyr::separate(Q3_8, Frage3, 
                        c("3_K1", "3_K2", "3_K3", "3_K4", "3_K5", "3_K6"), sep = " - ")
Q3_8_1 <- Q3_8[,c(7:12)]
names(Q3_8_1) <- Q3_8[1,c(1:6)]
Q3_8_2 <- Q3_8[,c(13:18)]
names(Q3_8_2) <- Q3_8[1,c(1:6)]
Q3_8_3 <- Q3_8[,c(19:24)]
names(Q3_8_3) <- Q3_8[1,c(1:6)]
cols <- c(1:ncol(Q3_8_1))
rows <- c(1:nrow(Q3_8_1))
for (c in cols){
  for (r in rows){
    if (Q3_8_1[r,c] == "Yes"){Q3_8_1[r,c] <- "Ja"}
    if (Q3_8_1[r,c] == "No"){Q3_8_1[r,c] <- "Nein"}
    if (Q3_8_1[r,c] == "I don't know"){Q3_8_1[r,c] <- "Weiß nicht"}
    if (Q3_8_2[r,c] == "Yes"){Q3_8_2[r,c] <- "Ja"}
    if (Q3_8_2[r,c] == "No"){Q3_8_2[r,c] <- "Nein"}
    if (Q3_8_3[r,c] == "Yes"){Q3_8_3[r,c] <- "Ja"}
    if (Q3_8_3[r,c] == "No"){Q3_8_3[r,c] <- "Nein"}
    if (Q3_8_3[r,c] == "I don't know"){Q3_8_3[r,c] <- "Weiß nicht"}
    if (Q3_8_1[r,c] == ""){Q3_8_1[r,c] <- NA}
    if (Q3_8_2[r,c] == ""){Q3_8_2[r,c] <- NA}
    if (Q3_8_3[r,c] == ""){Q3_8_3[r,c] <- NA}
  }
}
rm(cols, rows, c, r)

Q3_8_1_table <- data.frame(matrix(NA, ncol = 3, nrow = 6))
names(Q3_8_1_table) <- c("Ja", "Nein", "Weiß nicht")
Q3_8_1_table[1,1] <- length(which(Q3_8_1$`Genetische Zusammensetzung` == "Ja"))
Q3_8_1_table[1,2] <- length(which(Q3_8_1$`Genetische Zusammensetzung` == "Nein"))
Q3_8_1_table[1,3] <- length(which(Q3_8_1$`Genetische Zusammensetzung` == "Weiß nicht"))
Q3_8_1_table[2,1] <- length(which(Q3_8_1$`Art-Populationen` == "Ja"))
Q3_8_1_table[2,2] <- length(which(Q3_8_1$`Art-Populationen` == "Nein"))
Q3_8_1_table[2,3] <- length(which(Q3_8_1$`Art-Populationen` == "Weiß nicht"))
Q3_8_1_table[3,1] <- length(which(Q3_8_1$`Art-Eigenschaften` == "Ja"))
Q3_8_1_table[3,2] <- length(which(Q3_8_1$`Art-Eigenschaften` == "Nein"))
Q3_8_1_table[3,3] <- length(which(Q3_8_1$`Art-Eigenschaften` == "Weiß nicht"))
Q3_8_1_table[4,1] <- length(which(Q3_8_1$`Zusammensetzung einer Lebensgemeinschaft` == "Ja"))
Q3_8_1_table[4,2] <- length(which(Q3_8_1$`Zusammensetzung einer Lebensgemeinschaft` == "Nein"))
Q3_8_1_table[4,3] <- length(which(Q3_8_1$`Zusammensetzung einer Lebensgemeinschaft` == "Weiß nicht"))
Q3_8_1_table[5,1] <- length(which(Q3_8_1$`Ökosystem-Struktur` == "Ja"))
Q3_8_1_table[5,2] <- length(which(Q3_8_1$`Ökosystem-Struktur` == "Nein"))
Q3_8_1_table[5,3] <- length(which(Q3_8_1$`Ökosystem-Struktur` == "Weiß nicht"))
Q3_8_1_table[6,1] <- length(which(Q3_8_1$`Ökosystem-Funktion` == "Ja"))
Q3_8_1_table[6,2] <- length(which(Q3_8_1$`Ökosystem-Funktion` == "Nein"))
Q3_8_1_table[6,3] <- length(which(Q3_8_1$`Ökosystem-Funktion` == "Weiß nicht"))
Q3_8_1 <- t(Q3_8_1_table)
rm(Q3_8_1_table)
names(Q3_8_1) <- c("K1", "K2", "K3", "K4", "K5", "K6")

Q3_8_1_sum <- as.numeric(colSums(Q3_8_1))
names(Q3_8_1_sum) <- c("K1", "K2", "K3", "K4", "K5", "K6")
Q3_8_1_rel <- 100/Q3_8_1_sum*Q3_8_1
#row.names(Q3_8_1_rel) <- c("Ja", "Nein", "Weiß nicht")
row.names(Q3_8_1_rel) <- c("Yes", "No", "Don't know")
q3_8_1 <- barplot(Q3_8_1_rel,
        #main = "In welcher(n) Klasse(n) denken Sie sind Fernerkundungsdaten anwendbar?", 
        main = "In which class(es) do you think remote sensing data can be applied?", 
        sub = paste("mean n", "=", round(mean(Q3_8_1_sum), digits = 0), sep = " "),
        #names.arg = c("Genetik", "Art-Population", "Art-Eigenschaft", "Lebensgemeinschaft", "Ökosystem-Struktur", "Ökosystem-Funktion"),
        names.arg = c("Genetic comp.", "Spp. populations", "Spp. traits", "Community comp", "Eco. structure", "Eco. function"),
        ylim = c(0,max(Q3_8_1_rel)+20), yaxt='n',
        beside = TRUE, 
        legend.text = TRUE,
        args.legend = list("topright", bty = "n"),
        col = c("forestgreen", "firebrick", "grey"))
text(x = q3_8_1, y = Q3_8_1_rel, label = paste(round(Q3_8_1_rel, digits = 0), "%", " \n ", "n = ", Q3_8_1, sep = ""), pos = 3, cex = 1, col = "black")

Q3_8_2_table <- data.frame(matrix(NA, ncol = 2, nrow = 6))
names(Q3_8_2_table) <- c("Ja", "Nein")
Q3_8_2_table[1,1] <- length(which(Q3_8_2$`Genetische Zusammensetzung` == "Ja"))
Q3_8_2_table[1,2] <- length(which(Q3_8_2$`Genetische Zusammensetzung` == "Nein"))
Q3_8_2_table[2,1] <- length(which(Q3_8_2$`Art-Populationen` == "Ja"))
Q3_8_2_table[2,2] <- length(which(Q3_8_2$`Art-Populationen` == "Nein"))
Q3_8_2_table[3,1] <- length(which(Q3_8_2$`Art-Eigenschaften` == "Ja"))
Q3_8_2_table[3,2] <- length(which(Q3_8_2$`Art-Eigenschaften` == "Nein"))
Q3_8_2_table[4,1] <- length(which(Q3_8_2$`Zusammensetzung einer Lebensgemeinschaft` == "Ja"))
Q3_8_2_table[4,2] <- length(which(Q3_8_2$`Zusammensetzung einer Lebensgemeinschaft` == "Nein"))
Q3_8_2_table[5,1] <- length(which(Q3_8_2$`Ökosystem-Struktur` == "Ja"))
Q3_8_2_table[5,2] <- length(which(Q3_8_2$`Ökosystem-Struktur` == "Nein"))
Q3_8_2_table[6,1] <- length(which(Q3_8_2$`Ökosystem-Funktion` == "Ja"))
Q3_8_2_table[6,2] <- length(which(Q3_8_2$`Ökosystem-Funktion` == "Nein"))
Q3_8_2 <- t(Q3_8_2_table)
rm(Q3_8_2_table)
names(Q3_8_2) <- c("K1", "K2", "K3", "K4", "K5", "K6")

Q3_8_2_sum <- as.numeric(colSums(Q3_8_2))
names(Q3_8_2_sum) <- c("K1", "K2", "K3", "K4", "K5", "K6")
Q3_8_2_rel <- 100/Q3_8_2_sum*Q3_8_2
#row.names(Q3_8_2_rel) <- c("Ja", "Nein")
row.names(Q3_8_2_rel) <- c("Yes", "No")
q3_8_2 <- barplot(Q3_8_2_rel,
        #main = "In welcher(n) Klasse(n) wenden Sie bereits Fernerkundungsdaten an?", 
        main = "In which class(es) do you already use remote sensing data?", 
        sub = paste("mean n", "=", round(mean(Q3_8_2_sum), digits = 0), sep = " "),
        #names.arg = c("Genetik", "Art-Population", "Art-Eigenschaft", "Lebensgemeinschaft", "Ökosystem-Struktur", "Ökosystem-Funktion"),
        names.arg = c("Genetic comp.", "Spp. populations", "Spp. traits", "Community comp", "Eco. structure", "Eco. function"),
        ylim = c(0,max(Q3_8_2_rel)+20), yaxt='n',
        beside = TRUE, 
        legend.text = TRUE,
        args.legend = list("topright", bty = "n"),
        col = c("forestgreen", "firebrick"))
text(x = q3_8_2, y = Q3_8_2_rel, label = paste(round(Q3_8_2_rel, digits = 0), "%", " \n ", "n = ", Q3_8_2, sep = ""), pos = 3, cex = 1, col = "black")

Q3_8_3_table <- data.frame(matrix(NA, ncol = 3, nrow = 6))
names(Q3_8_3_table) <- c("Ja", "Nein", "Weiß nicht")
Q3_8_3_table[1,1] <- length(which(Q3_8_3$`Genetische Zusammensetzung` == "Ja"))
Q3_8_3_table[1,2] <- length(which(Q3_8_3$`Genetische Zusammensetzung` == "Nein"))
Q3_8_3_table[1,3] <- length(which(Q3_8_3$`Genetische Zusammensetzung` == "Weiß nicht"))
Q3_8_3_table[2,1] <- length(which(Q3_8_3$`Art-Populationen` == "Ja"))
Q3_8_3_table[2,2] <- length(which(Q3_8_3$`Art-Populationen` == "Nein"))
Q3_8_3_table[2,3] <- length(which(Q3_8_3$`Art-Populationen` == "Weiß nicht"))
Q3_8_3_table[3,1] <- length(which(Q3_8_3$`Art-Eigenschaften` == "Ja"))
Q3_8_3_table[3,2] <- length(which(Q3_8_3$`Art-Eigenschaften` == "Nein"))
Q3_8_3_table[3,3] <- length(which(Q3_8_3$`Art-Eigenschaften` == "Weiß nicht"))
Q3_8_3_table[4,1] <- length(which(Q3_8_3$`Zusammensetzung einer Lebensgemeinschaft` == "Ja"))
Q3_8_3_table[4,2] <- length(which(Q3_8_3$`Zusammensetzung einer Lebensgemeinschaft` == "Nein"))
Q3_8_3_table[4,3] <- length(which(Q3_8_3$`Zusammensetzung einer Lebensgemeinschaft` == "Weiß nicht"))
Q3_8_3_table[5,1] <- length(which(Q3_8_3$`Ökosystem-Struktur` == "Ja"))
Q3_8_3_table[5,2] <- length(which(Q3_8_3$`Ökosystem-Struktur` == "Nein"))
Q3_8_3_table[5,3] <- length(which(Q3_8_3$`Ökosystem-Struktur` == "Weiß nicht"))
Q3_8_3_table[6,1] <- length(which(Q3_8_3$`Ökosystem-Funktion` == "Ja"))
Q3_8_3_table[6,2] <- length(which(Q3_8_3$`Ökosystem-Funktion` == "Nein"))
Q3_8_3_table[6,3] <- length(which(Q3_8_3$`Ökosystem-Funktion` == "Weiß nicht"))
Q3_8_3 <- t(Q3_8_3_table)
rm(Q3_8_3_table)
names(Q3_8_3) <- c("K1", "K2", "K3", "K4", "K5", "K6")

Q3_8_3_sum <- as.numeric(colSums(Q3_8_3))
names(Q3_8_3_sum) <- c("K1", "K2", "K3", "K4", "K5", "K6")
Q3_8_3_rel <- 100/Q3_8_3_sum*Q3_8_3
#row.names(Q3_8_3_rel) <- c("Ja", "Nein", "Weiß nicht")
row.names(Q3_8_3_rel) <- c("Ja", "Nein", "Weiß nicht")
q3_8_3 <- barplot(Q3_8_3_rel,
        #main = "In welcher(n) Klasse(n) benötigt man Ihrer Meinung nach unbedingt in-situ-Daten?", 
        main = "In which class(es) do you think in-situ data are absolutely necessary?", 
        sub = paste("mean n", "=", round(mean(Q3_8_3_sum), digits = 0), sep = " "),
        #names.arg = c("Genetik", "Art-Population", "Art-Eigenschaft", "Lebensgemeinschaft", "Ökosystem-Struktur", "Ökosystem-Funktion"),
        names.arg = c("Genetic comp.", "Spp. populations", "Spp. traits", "Community comp", "Eco. structure", "Eco. function"),
        ylim = c(0,max(Q3_8_3_rel)+20), yaxt='n',
        beside = TRUE, 
        legend.text = TRUE,
        args.legend = list("topright", bty = "n"),
        col = c("forestgreen", "firebrick", "grey"))
text(x = q3_8_3, y = Q3_8_3_rel, label = paste(round(Q3_8_3_rel, digits = 0), "%", " \n ", "n = ", Q3_8_3, sep = ""), pos = 3, cex = 1, col = "black")
```

```{r Q4_1, eval=FALSE}
Q4_1 <- factor(ergebnisse$X4_1, levels = c("4_1_a", "4_1_b"))

Q4_1_sum <- as.numeric(table(Q4_1))
#names(Q4_1_sum) <- c("Männlich", "Weiblich")
names(Q4_1_sum) <- c("Male", "Female")
Q4_1_rel <- 100/sum(Q4_1_sum)*Q4_1_sum
q4_1 <- barplot(Q4_1_rel,
        #main = "Geschlecht", 
        main = "Gender", 
        sub = paste("total n", "=", length(ergebnisse$X4_1[!is.na(ergebnisse$X4_1) == T]), sep = " "),
        #names.arg = c("Männlich", "Weiblich"),
        names.arg = c("Male", "Female"),
        ylim = c(0,max(Q4_1_rel)+5), yaxt='n')
text(x = q4_1, y = Q4_1_rel, label = paste(round(Q4_1_rel, digits = 0), "%", " \n ", "n = ", Q4_1_sum, sep = ""), pos = 3, cex = 1, col = "black")

labls <- paste(names(Q4_1_rel), "\n", round(Q4_1_rel, digits = 0), "%", sep = "")
pie(Q4_1_rel, labels = labls, col = c(rgb(128,179,87,max=255), rgb(69,121,163,max=255)))
```

```{r Q4_2, eval=FALSE}
Q4_2 <- factor(ergebnisse$X4_2, levels = c("4_2_a", "4_2_b", "4_2_c", "4_2_d", "4_2_e", "4_2_f"))

Q4_2_sum <- as.numeric(table(Q4_2))
names(Q4_2_sum) <- c("4_2_a", "4_2_b", "4_2_c", "4_2_d", "4_2_e", "4_2_f")
Q4_2_rel <- 100/sum(Q4_2_sum)*Q4_2_sum
q4_2 <- barplot(Q4_2_rel,
        #main = "Alter", 
        main = "Age", 
        sub = paste("total n", "=", length(ergebnisse$X4_2[!is.na(ergebnisse$X4_2) == T]), sep = " "),
        #names.arg = c("18-24 Jahre", "25-34 Jahre", "35-44 Jahre", "45-59 Jahre", "60-69 Jahre", "70 Jahre und älter"),
        names.arg = c("18-24 years", "25-34 years", "35-44 years", "45-59 years", "60-69 years", "70 years and older"),
        ylim = c(0,max(Q4_2_rel)+5), yaxt='n', col = rgb(69,121,163, max=255))
text(x = q4_2, y = Q4_2_rel, label = paste(round(Q4_2_rel, digits = 0), "%", " \n ", "n = ", Q4_2_sum, sep = ""), pos = 3, cex = 1, col = "black")
```

```{r Q4_3, eval=FALSE}
Q4_3 <- factor(ergebnisse$X4_3, levels = c("4_3_a", "4_3_b", "4_3_c", "4_3_d", "4_3_e", "4_3_f", "4_3_g", "4_3_h", "4_3_i", "4_3_j"))

Q4_3_sum <- as.numeric(table(Q4_3))
#names(Q4_3_sum) <- c("Hauptsch.", "Realsch.", "Abitur", "Bachelor", "Master", "Diplom", "Examen", "Promotion", "Habilitation", "anderer")
names(Q4_3_sum) <- c("2nd school low", "2nd school medium", "2nd school high", "Bachelor", "Master", "Diploma", "State examination", "PhD", "Habilitation", "other")
Q4_3_rel <- 100/sum(Q4_3_sum)*Q4_3_sum
q4_3 <- barplot(Q4_3_rel,
        #main = "Höchster Bildungsabschluss", 
        main = "Highest educational achievement", 
        sub = paste("total n", "=", length(ergebnisse$X4_3[!is.na(ergebnisse$X4_3) == T]), sep = " "),
        #names.arg = c("Hauptsch.", "Realsch.", "Abitur", "Bachelor", "Master", "Diplom", "Examen", "Promotion", "Habilitation", "anderer"),
        names.arg = c("2nd school low", "2nd school medium", "2nd school high", "Bachelor", "Master", "Diploma", "State examination", "PhD", "Habilitation", "other"),
        ylim = c(0,max(Q4_3_rel)+5), yaxt='n')
text(x = q4_3, y = Q4_3_rel, label = paste(round(Q4_3_rel, digits = 0), "%", " \n ", "n = ", Q4_3_sum, sep = ""), pos = 3, cex = 1, col = "black")

labls <- paste(c(names(Q4_3_rel[c(5,6,8,9)]), "other"), #"anderer"), 
               "\n", c(round(Q4_3_rel[c(5,6,8,9)], digits = 0), 100-sum(round(Q4_3_rel[c(5,6,8,9)], digits = 0))), "%", sep = "")
pie(c(Q4_3_rel[c(5,6,8,9)], (100-sum(Q4_3_rel[c(5,6,8,9)], digits = 0))), labels = labls, 
    col = c(rgb(128,179,87,max=255), rgb(173,198,70,max=255), rgb(69,121,163,max=255), rgb(86,151,205,max=255), NA))
```

```{r Q4_4, eval=FALSE}
Q4_4 <- factor(ergebnisse$X4_4, levels = c("4_4_a", "4_4_b", "4_4_c", "4_4_d", "4_4_e", "4_4_f", "4_4_g", "4_4_h", "4_4_i"))

Q4_4_sum <- as.numeric(table(Q4_4))
names(Q4_4_sum) <- c("4_4_a", "4_4_b", "4_4_c", "4_4_d", "4_4_e", "4_4_f", "4_4_g", "4_4_h", "4_4_i")
Q4_4_rel <- 100/sum(Q4_4_sum)*Q4_4_sum
q4_4 <- barplot(Q4_4_rel,
        #main = "Aktuelle Tätigkeit", 
        main = "Current function", 
        sub = paste("total n", "=", length(ergebnisse$X4_4[!is.na(ergebnisse$X4_4) == T]), sep = " "),
        #names.arg = c("Professor_in", "Post-Doc", "Wiss.Mit.", "Doktorand_in", "Student_in", "Techn. Ang.", "Admin.", "ÖA", "andere"),
        names.arg = c("Professor", "Post-Doc", "Sc. officer", "PhD student", "Student", "Techn. staff", "Admin. staff", "PR", "other"),
        ylim = c(0,max(Q4_4_rel)+5), yaxt='n', col = rgb(69,121,163, max=255))
text(x = q4_4, y = Q4_4_rel, label = paste(round(Q4_4_rel, digits = 0), "%", " \n ", "n = ", Q4_4_sum, sep = ""), pos = 3, cex = 1, col = "black")
```

```{r Q4_5, eval=FALSE}
Q4_5 <- factor(ergebnisse$X4_5, levels = c("4_5_a", "4_5_b", "4_5_c", "4_5_d", "4_5_e"))

Q4_5_sum <- as.numeric(table(Q4_5))
names(Q4_5_sum) <- c("4_5_a", "4_5_b", "4_5_c", "4_5_d", "4_5_e")
Q4_5_rel <- 100/sum(Q4_5_sum)*Q4_5_sum
q4_5 <- barplot(Q4_5_rel,
        #main = "Welcher Kategorie ordnen Sie Ihren Arbeitgeber am ehesten zu?", 
        main = "Which category best describes your employer?", 
        sub = paste("total n", "=", length(ergebnisse$X4_5[!is.na(ergebnisse$X4_5) == T]), sep = " "),
        #names.arg = c("Akad. Forschung", "Akad. Forschung/Lehre", "Behörde", "Wirtschaft", "Verein"),
        names.arg = c("Acad. research", "Acad. research and teaching", "Pub. authority", "Private sector", "NGO"),
        ylim = c(0,max(Q4_5_rel)+5), yaxt='n', col = rgb(69,121,163, max=255))
text(x = q4_5, y = Q4_5_rel, label = paste(round(Q4_5_rel, digits = 0), "%", " \n ", "n = ", Q4_5_sum, sep = ""), pos = 3, cex = 1, col = "black")
```

```{r Q4_6, eval=FALSE}
Q4_6 <- ergebnisse[,c(115:118)]
Q4_6 <- transform(Q4_6, X4_6_a = as.numeric(X4_6_a), 
                        X4_6_b = as.numeric(X4_6_b), 
                        X4_6_c = as.numeric(X4_6_c), 
                        X4_6_d = as.numeric(X4_6_d))

Q4_6_sum <- colSums(Q4_6, na.rm = TRUE)
#names(Q4_6_sum) <- c("Lokal/ regional in Deutschland", "National in Deutschland", "Europa", "International")
names(Q4_6_sum) <- c("Locally/ regionally within Germany", "Nationally in whole Germany", "European scale", "Internationally")
Q4_6_rel <- 100/sum(Q4_6_sum)*Q4_6_sum
q4_6 <- barplot(Q4_6_rel,
        #main = "In welcher Skala findet Ihre Anwendung der Biodiversitätsdaten statt?", 
        main = "At what scale do you apply biodiversity data?", 
        sub = paste("total n", "=", length(which(rowSums(Q4_6, na.rm=T)!=0)), sep = " "),
        #names.arg = c("Lokal in D.", "National in D.", "Europa", "International"),
        names.arg = c("Locally in G.", "Nationally in G", "Europe", "Internationally"),
        ylim = c(0,max(Q4_6_rel)+5), yaxt='n')
text(x = q4_6, y = Q4_6_rel, label = paste(round(Q4_6_rel, digits = 0), "%", " \n ", "n = ", Q4_6_sum, sep = ""), pos = 3, cex = 1, col = "black")

labls <- paste(names(Q4_6_rel), "\n", round(Q4_6_rel, digits = 0), "%", sep = "")
pie(Q4_6_rel, labels = labls, col = c(rgb(128,179,87,max=255), rgb(173,198,70,max=255), rgb(69,121,163,max=255), rgb(86,151,205,max=255)))
```



```{r xRest, eval=FALSE}

# Quantitative Antworten
results <- xlsx::read.xlsx(file = "Daten/results.xlsx", sheetIndex = 1, encoding="UTF-8")
Q1_1 <- factor(results$Q1_1, levels = c("Datenbereitstellung", 
                                        "Datenaufbereitung",
                                        "Datenverschmelzung",
                                        "Mit keinem 'dieser' Schritte"))
Q1_2 <- factor(results$Q1_2, levels = c("0 bis 25%", 
                                        "26 bis 50%",
                                        "51 bis 75%",
                                        "76 bis 100%"))
Q2_1 <- factor(results$Q2_1, levels = c("Ja", 
                                        "Nein"))
Q2_4 <- factor(results$Q2_4, levels = c("Ja", 
                                        "Nein",
                                        "In Teilen"))
Q3_1 <- factor(results$Q3_1, levels = c("Ja", 
                                        "Nein"))
Q3_2 <- factor(results$Q3_2, levels = c("Light Detection and Ranging (LIDAR)", 
                                        "Radio Detection and Ranging (RADAR)",
                                        "Multispektrale Bilder",
                                        "Hyperspektrale Bilder",
                                        "Wärmebilder",
                                        "Luftbilder/ Orthophotos",
                                        "Andere"))
Q3_3 <- factor(results$Q3_3, levels = c("Biodiversitätsmonitoring", 
                                        "Politische Berichterstattung",
                                        "Forschung",
                                        "Planung",
                                        "Beratung",
                                        "Andere privatwirtschaftliche Zwecke"))
Q3_5 <- factor(results$Q3_5, levels = c("Deutsche Nationale Biodiversitätsstrategie", 
                                        "Europäische Biodiversitätsstrategie",
                                        "Gemeinsame Agrarpolitik der EU (GAP)",
                                        "Natura 2000",
                                        "Fauna-Flora-Habitat-Richtlinie (FFH)",
                                        "Übereinkommen über die biologische Vielfalt (CBD)",
                                        "Intergovernmental science-policy Platform on Biodiversity and Ecosystem Services (IPBES)",
                                        "Washingtoner Artenschutzabkommen (CITES",
                                        "Übereinkommen zur Erhaltung wandernder wild lebender Tierarten (CMS)",
                                        "Abkommen zur Erhaltung der europäischen Fledermauspopulationen (EUROBATS)",
                                        "Übereinkommen über Feuchtgebiete (Ramsar)",
                                        "Group on Earth Observations (GEO)",
                                        "Andere"))
Q4_1 <- factor(results$Q4_1, levels = c("Männlich", 
                                        "Weiblich"))
Q4_2 <- factor(results$Q4_2, levels = c("25-34 Jahre", 
                                        "35-44 Jahre", 
                                        "45-59 Jahre", 
                                        "60-69 Jahre", 
                                        "70 Jahre und älter"))
Q4_3 <- factor(results$Q4_3, levels = c("Sekundarstufe II", 
                                        "Abitur", 
                                        "Master", 
                                        "Diplom", 
                                        "Promotion", 
                                        "Habilitation"))
Q4_4 <- factor(results$Q4_4, levels = c("Professor_in",
                                        "Post-Doc",
                                        "Wissenschaftliche_r Angestellte_r ohne Doktortitel",
                                        "Doktorand_in",
                                        "Technische_r Angestellte_r",
                                        "Angestellte_r in Administration und Management",
                                        "Andere"))
Q4_5 <- factor(results$Q4_5, levels = c("Akademische Tätigkeit: Forschung",
                                        "Akademische Tätigkeit: Forschung und Lehre",
                                        "Regierung oder Behörde",
                                        "Privatwirtschaft",
                                        "Verein oder NGO"))
Q4_6 <- factor(results$Q4_6, levels = c("Lokal/ Regional innerhalb Deutschland",
                                        "National in Gesamt-Deutschland",
                                        "Europa",
                                        "International (über Europa hinaus)"))

Q2_2 <- xlsx::read.xlsx(file = "Daten/results.xlsx", sheetIndex = 2, encoding="UTF-8")
row.names(Q2_2) <- Q2_2[,1]
Q2_2 <- t(Q2_2[,-1])

Q2_3 <- xlsx::read.xlsx(file = "Daten/results.xlsx", sheetIndex = 3, encoding="UTF-8")
row.names(Q2_3) <- Q2_3[,1]
Q2_3 <- t(Q2_3[,-1])

Q3_4 <- xlsx::read.xlsx(file = "Daten/results.xlsx", sheetIndex = 4, encoding="UTF-8")
row.names(Q3_4) <- Q3_4[,1]
Q3_4 <- t(Q3_4[,-1])


```

